/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

/**
 *
 * @author maw136
 */
public class GameGUI extends javax.swing.JFrame {

    /**
     * Creates new form GameGUI
     */
    Deck d = new Deck();
    int i=0;
    public GameGUI() {
        initComponents();
        d.shuffle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Deal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 81, 114));
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 81, 114));
        jLayeredPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 86, 114));
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 90, 114));
        jLayeredPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 110));
        jLayeredPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 80, 110));
        jLayeredPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 81, 110));
        jLayeredPane1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 81, 110));
        jLayeredPane1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 86, 114));
        jLayeredPane1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 86, 114));

        jButton2.setText("Sort");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        i=i+8;
        if(i>=46)
            i=0;
        Card c1 = d.deck.get(i);
        Card c2 = d.deck.get(i+1);
        Card c3 = d.deck.get(i+2);
        Card c4 = d.deck.get(i+3);
        Card c5 = d.deck.get(i+8);
        Card h1 = d.deck.get(i+4);
        Card h2 = d.deck.get(i+5);
        Card h3 = d.deck.get(i+6);
        Card h4 = d.deck.get(i+7);
        Card h5 = d.deck.get(i+9);
    
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/"+ h1.getImage())));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + h2.getImage())));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/"+ h3.getImage())));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + h4.getImage())));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + c1.getImage())));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + c2.getImage() )));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + c3.getImage())));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + c4.getImage())));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + c5.getImage())));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + h5.getImage())));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Card c1 = d.deck.get(i);
        Card c2 = d.deck.get(i+1);
        Card c3 = d.deck.get(i+2);
        Card c4 = d.deck.get(i+3);
        Card c5 = d.deck.get(i+8);
        Card h1 = d.deck.get(i+4);
        Card h2 = d.deck.get(i+5);
        Card h3 = d.deck.get(i+6);
        Card h4 = d.deck.get(i+7);
        Card h5 = d.deck.get(i+9);
        Hand CPU = new Hand(c1,c2,c3,c4,c5);
        Hand human = new Hand(h1,h2,h3,h4,h5);
       
        human.sort();
        CPU.sort();
        
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/"+ human.hand.get(0).getImage())));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + human.hand.get(1).getImage())));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/"+ human.hand.get(2).getImage())));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + human.hand.get(3).getImage())));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + human.hand.get(4).getImage())));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + CPU.hand.get(0).getImage())));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + CPU.hand.get(1).getImage())));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + CPU.hand.get(2).getImage())));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + CPU.hand.get(3).getImage())));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/images/" + CPU.hand.get(4).getImage())));
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
